version: '3.9'

services:
  web:
    build: .
    container_name: luxauto_web
    ports:
      - "8000:8000"
    env_file:
      - .ENV
    depends_on:
      - db
    volumes:
      - .:/app # live reload
    command: python app.py # Start de app handmatig


  db:
    image: postgres:15
    container_name: luxauto_db
    env_file:
      - .ENV
    environment:
      TZ: Europe/Amsterdam
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"   # <-- hier naar 5433 veranderen, omdat andere port kan bezet zijn

  pgadmin:
    image: dpage/pgadmin4
    container_name: luxauto_pgadmin
    env_file:
      - .ENV
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
