version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .ENV
    environment:
      - FLASK_APP=app.py
    depends_on:
      - db
    volumes:
      - .:/app # live reload
    command: python app.py # Start de app handmatig


  db:
    image: postgres:15
    restart: always
    env_file:
      - .ENV
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"   # <-- hier naar 5433 veranderen, omdat andere port kan bezet zijn

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@autolux.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
