services:
  db:
    image: postgres:15
    container_name: LuxAuto_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: autolux_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: LuxAuto
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    container_name: LuxAuto_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: luxe@auto.com
      PGADMIN_DEFAULT_PASSWORD: LuxeAuto123
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin  # ← permanent PGAdmin serveropslag

volumes:
  postgres_data:
  pgadmin_data:
